---
title: "Threatened species script"
format: html
editor: visual
knitr:
  opts_knit:
    root.dir: "C:/Users/Lizzy/Documents/GitHub/threatened_species_traits"
---

## load, build

```{r}
library(tidyverse)
library(remake)
library(austraits)
library(APCalign)
library(traits.build)

resources <- APCalign::load_taxonomic_resources()

austraits <- readRDS("C:/Users/Lizzy/Documents/GitHub/threatened_species_traits/ignore/austraits/austraits-6.0.0.rds")

source("C:/Users/Lizzy/Documents/GitHub/threatened_species_traits/R/custom_R_code.R")
source("C:/Users/Lizzy/Documents/GitHub/threatened_species_traits/R/extra_functions.R")

setwd("C:/Users/Lizzy/Documents/GitHub/threatened_species_traits")
build_setup_pipeline(method = "remake", database_name = "threatened_species")

threatened_species <- remake::make("threatened_species")
```

```{r}
current_study <- "Pegg_2018"

excluded <- threatened_species$excluded_data %>% filter(dataset_id == current_study)
View(excluded)

traits_for_study <- threatened_species$traits %>% filter(dataset_id == current_study)
View(traits_for_study)
```

# habitat

```{r}
rainforest <- (austraits %>%
  extract_dataset(c("ATRP_2020", "Cooper_2013", "Cooper_2004")))$traits %>%
  distinct(taxon_name, dataset_id) %>%
  group_by(taxon_name) %>%
  mutate(source_id = paste0(dataset_id, collapse = "; ")) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "rainforest")

rainforest2 <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = c("rainforest", "tropical moist forest", "rain forest")))$traits %>%
  filter(!dataset_id %in% c("ATRP_2020", "Cooper_2013", "Cooper_2004")) %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "rainforest")

aquatic <- (austraits %>%
  extract_trait("plant_growth_substrate") %>%
  extract_data(table = "traits", col = "value", col_value = "aquatic"))$traits %>%
  tidyr::separate_longer_delim(cols = value, delim = " ") %>%
  distinct(taxon_name, value, dataset_id) %>%
  filter(str_detect(value, "aquatic")) %>%
  group_by(taxon_name, value) %>%
  mutate(source_id = paste0(dataset_id, collapse = "; ")) %>%
  ungroup() %>%
  distinct(taxon_name, value, source_id) %>%
  group_by(taxon_name, source_id) %>%
  mutate(habitat = paste0(value, collapse = " ")) %>%
  ungroup() %>%
  distinct(taxon_name, habitat, source_id)

wet_sclerophyll <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = "wet sclerophyll"))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "wet_sclerophyll")

dry_sclerophyll <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = "dry sclerophyll"))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "dry_sclerophyll")

wet_heath <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = "wet heath"))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "wet_heath")

heath <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = "heath"))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "heath")

grassland <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = c("grassland", "spinifex")))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "grassland")

savanna <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = c("savanna")))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "grassland")

bogs_fens <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = c("bog", "fen")))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "bogs")

shrubland <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = c("shrubland", "scrub", "mallee")))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "shrubland")

eucalypt_forest <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = c("eucalypt forest")))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "eucalypt_forest")

closed_forest <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = c("closed forest")))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "closed_forest")

alpine <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = c("alpine")))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "alpine")

open_forest <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = c("open forest")))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "open_forest")

dry_forest <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = c("dry forest")))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "dry_forest")

wet_forest <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = c("wet forest")))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "wet_forest")


woodland <- (austraits %>%
  extract_data(table = "locations", col = "location_property", col_value = c("habitat", "description")) %>%
  extract_data(table = "locations", col = "value", col_value = c("woodland")))$traits %>%
  select(taxon_name, dataset_id) %>% 
  distinct() %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(dataset_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct(taxon_name, source_id) %>%
  mutate(habitat = "woodland")

habitats <- aquatic %>%
  bind_rows(alpine, bogs_fens, closed_forest, dry_forest, dry_sclerophyll,  eucalypt_forest, grassland, heath, open_forest, rainforest, rainforest2, savanna, shrubland, wet_heath, wet_forest, wet_sclerophyll, woodland) %>%
  group_by(taxon_name) %>%
  mutate(
    source_id = paste0(source_id, collapse = "; ")
  ) %>%
  ungroup() %>%
  distinct() %>%
  group_by(taxon_name, source_id)  %>%
  mutate(
    habitat = paste0(habitat, collapse = " ")
  )%>%
  ungroup() %>%
  distinct()

habitats <- habitats %>%
  tidyr::separate_longer_delim(cols = source_id, delim = "; ") %>%
  distinct() %>%
  arrange(source_id) %>%
  group_by(taxon_name, habitat) %>%
  mutate(source_id = paste0(source_id, collapse = "; ")) %>%
  ungroup() %>%
  distinct() %>%
  tidyr::separate_longer_delim(cols = habitat, delim = " ") %>%
  distinct() %>%
  arrange(habitat) %>%
  group_by(taxon_name, source_id) %>%
  mutate(habitat = paste0(habitat, collapse = " ")) %>%
  ungroup() %>%
  distinct()

habitats %>% write_csv("data/AusTraits_habitats_2024/data.csv")
```

# tables with key traits
```{r}
habitat <- threatened_species$traits %>%
  filter(trait_name == "habitat") %>%
  select(taxon_name, habitat = value) %>%
  group_by(taxon_name) %>%
  mutate(habitat = paste0(habitat, collapse = " ")) %>%
  ungroup()

myrtle_rust_susceptibility <- threatened_species$traits %>%
  filter(trait_name == "myrtle_rust_susceptibility") %>%
  select(taxon_name, myrtle_rust_susceptibility = value) %>%
  group_by(taxon_name) %>%
  mutate(myrtle_rust_susceptibility = paste0(myrtle_rust_susceptibility, collapse = " ")) %>%
  ungroup() %>%
  distinct()

categorical_traits_from_austraits <- austraits$traits %>%
  filter(trait_name %in% c("nitrogen_fixing", "dispersal_syndrome")) %>%
  filter(taxon_name %in% resources$`APC list (accepted)`$canonical_name) %>%
  select(taxon_name, trait_name, value, dataset_id) %>%
  tidyr::separate_longer_delim(value, delim = " ") %>%
  group_by(taxon_name, trait_name, value) %>%
  mutate(
    count = n()#,
    #source_id = paste0(dataset_id, collapse = "; ")
    ) %>%
  ungroup() %>%
  select(-dataset_id) %>%
  distinct() %>%
  mutate(value = paste0(value, " (", count, ")")) %>%
  select(-count) %>%
  group_by(taxon_name, trait_name) %>%
  mutate(value = paste0(value, collapse = "; ")) %>%
  ungroup() %>%
  distinct() %>%
  tidyr::pivot_wider(names_from = trait_name, values_from = value)

seed_dry_mass <- austraits %>%
  austraits::extract_trait("seed_dry_mass") %>%
  austraits_weighted_means("seed_dry_mass") %>%
  filter(taxon_name %in% resources$`APC list (accepted)`$canonical_name) %>%
  select(taxon_name, seed_dry_mass = mean)
```

# probability script

# TODO - assign to zero species where the entire range falls in locations with wet season rainfall above threshhold, or temp above threshold, etc.
```{r}
probability_0_1 <- resources$APC %>% 
  filter(taxonomic_status == "accepted") %>%
  filter(taxon_rank %in% c("species", "subspecies", "variety")) %>%
  select(taxon_name = canonical_name, family, taxon_distribution) %>%
  left_join(habitat, by = "taxon_name") %>%
  mutate(susceptibility_step_1 = ifelse(family == "Myrtaceae", 1, 0)) %>%
  mutate(susceptibility_step_2 = ifelse(str_detect(habitat, "rainforest") | str_detect(habitat, "wet") | str_detect(habitat, "aquatic")| str_detect(habitat, "bogs"), 1, 0)) %>%
 mutate(susceptibility_binary = ifelse(susceptibility_step_1 == 1 & (susceptibility_step_2 == 1| is.na(susceptibility_step_2)), 1, 0))
```

```{r}
probability_0_1 <- probability_0_1 %>%
  filter(susceptibility_binary == 1) %>%
  left_join(myrtle_rust_susceptibility, by = "taxon_name") %>%
  mutate(
    myrtle_rust_susceptibility_numeric = case_when(
      myrtle_rust_susceptibility == "resistant" ~ 0,
      myrtle_rust_susceptibility == "low resistant" ~ 0.5,
      myrtle_rust_susceptibility == "low" ~ 1,
      myrtle_rust_susceptibility == "medium resistant" ~ 1.5,
      myrtle_rust_susceptibility == "resistant susceptible" ~ 1.5,
      myrtle_rust_susceptibility == "susceptible resistant susceptible" ~ 2,
      myrtle_rust_susceptibility == "low medium" ~ 2,
      myrtle_rust_susceptibility == "high resistant" ~ 2.5,
      myrtle_rust_susceptibility == "medium" ~ 3,
      myrtle_rust_susceptibility == "high low" ~ 3,
      myrtle_rust_susceptibility == "susceptible" ~ 3,
      myrtle_rust_susceptibility == "high medium high resistant" ~ 3,
      myrtle_rust_susceptibility == "low medium high medium resistant high" ~ 3,
      myrtle_rust_susceptibility == "susceptible medium" ~ 3,
      myrtle_rust_susceptibility == "susceptible high resistant" ~ 3,
      myrtle_rust_susceptibility == "high medium" ~ 4,
      myrtle_rust_susceptibility == "high" ~ 5
    )
  ) %>%
  left_join(categorical_traits_from_austraits) %>%
  left_join(seed_dry_mass)
```


# myrtle rust

```{r}
# species in APC that are in Myrtaceae
Myrtaceae <- resources$APC %>% 
  filter(taxonomic_status == "accepted") %>%
  filter(family == "Myrtaceae") %>% 
  filter(taxon_rank %in% c("species", "subspecies", "variety", "form")) %>%
  select(canonical_name, family, taxon_distribution, name_type, taxon_ID)



# species for which myrtle rust status is known
myrtle_rust_susceptibility_known <- threatened_species$traits %>% 
  filter(trait_name == "myrtle_rust_susceptibility") %>%
  group_by(taxon_name) %>%
  mutate(
    dataset_id = paste0(dataset_id, collapse = "; "),
    value = paste0(value, collapse = "; "),
    value_type = paste0(value_type, collapse = "; ")
    ) %>%
  ungroup() %>%
  distinct(taxon_name, dataset_id, trait_name, value, value_type)



# extra N-fixing
austraits$traits %>% 
  filter(trait_name == "nitrogen_fixing") %>% 
  distinct(taxon_name, trait_name, value) %>%
  group_by(taxon_name, trait_name) %>%
  
  ungroup()
```

The `echo: false` option disables the printing of code (only output is displayed).


