---
title: "threatened_species_scripts"
format: html
editor: visual
---

## startup

```{r}
library(tidyverse)
library(remake)
library(traits.build)
library(austraits)
source("R/custom_R_code.R")

build_setup_pipeline(method = "base", database_name = "threatened_species")
build_setup_pipeline(method = "remake", database_name = "threatened_species")

austraits <- readRDS("data/austraits/austraits-6.0.0.rds")

threatened_species <- remake::make("threatened_species")

list_of_threatened_species <- threatened_species %>% 
  filter(dataset_id == "DCCEEW_2024") %>%
  
  select(taxon_name, value)
  
phytophthora <- read_csv("data/datasets_from_manuscripts/Phytophthora_abatement_plant_Appendix4.csv")
```

```{r}
species <- "Styphelia perileuca"

austraits$traits %>% filter(taxon_name == species) %>% View()

read_csv("data/threatened_species_masterlist.csv") %>%
  left_join(austraits$taxa %>% select(suggested_name = taxon_name, family)) %>%
  write_csv("data/threatened_species_masterlist.csv")
```

```{r}
App4 <- read_csv("data/datasets_from_manuscripts/Phytophthora_abatement_plant_Appendix4.csv")
OGara_all <- read_csv("data/datasets_from_manuscripts/OGara_2006_all_columns.csv")

App4_corrected_names <- APCalign::create_taxonomic_update_lookup(App4$Species, full = TRUE)
App4_corrected_names_tmp <- App4_corrected_names %>% select(original_name, suggested_name, accepted_name, family, taxon_distribution) %>% rename(Species = original_name) 

App4 <- App4 %>% distinct(Species, .keep_all = TRUE) %>% left_join(App4_corrected_names_tmp)

App4 %>% filter(suggested_name %in% threatened_species$suggested_name)

write_csv(App4, "data/datasets_from_manuscripts/Phytophthora_abatement_plant_Appendix4.csv", na="")

data_McDougall_2024a <- read_csv("data/datasets_from_manuscripts/data_McDougall_2024a.csv")

data_McDougall_2024a_corrected_names <- APCalign::create_taxonomic_update_lookup(data_McDougall_2024a$Species, full = TRUE, resources = resources)

data_McDougall_2024a_corrected_names_tmp <- data_McDougall_2024a_corrected_names %>% select(original_name, suggested_name, accepted_name, family, taxon_distribution) %>% rename(Species = original_name) 

data_McDougall_2024a <- data_McDougall_2024a %>% distinct(Species, .keep_all = TRUE) %>% left_join(data_McDougall_2024a_corrected_names_tmp)

write_csv(data_McDougall_2024a, "data/datasets_from_manuscripts/data_McDougall_2024a.csv", na="")

App4 %>% filter(!suggested_name %in% data_McDougall_2024a$suggested_name) %>% left_join(OGara_all) %>% View()

data_McDougall_2024a %>% filter(!suggested_name %in% App4$suggested_name)
```

```{r}
flowering_times <- austraits$traits %>% 
  filter(trait_name == "flowering_time") %>% 
  select(taxon_name, dataset_id, trait_name, value) %>%
  group_by(taxon_name, dataset_id, trait_name) %>%
  mutate(value = first(value)) %>%
  ungroup() %>%
  group_by(taxon_name, trait_name) %>%
  mutate(
    value = paste0(value, collapse = "--"),
    dataset_id = paste0(dataset_id, collapse = "--")
  ) %>%
  ungroup() %>%
  distinct()
```

```{r}
growth_form_exists <- austraits$traits %>% 
  filter(trait_name == "plant_growth_form") %>% 
  distinct(taxon_name)

growth_form_exists_updates <- create_taxonomic_update_lookup(growth_form_exists$taxon_name) 

threatened_species %>% filter(!suggested_name %in% growth_form_exists_updates$accepted_name) %>% left_join(growth_form_exists_updates %>% select(suggested_name = accepted_name, original_name)) -> v1

threatened_species %>% filter(!suggested_name %in% growth_form_exists$taxon_name) -> v2
```

```{r}
LMA_means <- austraits$traits %>% 
  filter(trait_name == "leaf_mass_per_area") %>% 
  filter(str_detect(life_stage, "adult")) %>% 
  filter(basis_of_record == "field") %>% 
  select(taxon_name, value) %>% 
  group_by(taxon_name) %>% 
  summarise(
    value = mean(as.numeric(value))
  ) %>%
  ungroup()
```

```{r}
nitrogen_fixing <- austraits$traits %>% 
  filter(trait_name == "nitrogen_fixing") %>% 
  select(taxon_name, value) %>% 
  group_by(taxon_name) %>% 
  mutate(
    value = paste0(value, collapse = "-")
  ) %>%
  ungroup() %>%
  select(taxon_name, nitrogen_fixing = value) %>%
  distinct()


phytophthora_with_N_fixing <- phytophthora %>%
  left_join(nitrogen_fixing %>% rename(suggested_name = taxon_name))
```

```{r}
resprouting_capacity <- austraits$traits %>% 
  filter(trait_name == "resprouting_capacity") %>%
  select(taxon_name, value) %>% 
  mutate(value_numeric = case_when(
      value == "fire_killed" ~ 0,
      value == "resprouts" ~ 1,
      value == "fire_killed resprouts" ~ 0.5,
      value == "partial_resprouting" ~ 0.5,
      value == "fire_killed partial_resprouting" ~ 0.25,
      value == "partial_resprouting resprouts" ~ 0.75,
      value == "fire_killed partial_resprouting resprouts" ~0.5
    )
  ) %>%
  select(-value) %>%
  group_by(taxon_name) %>% 
  summarise(
    value_numeric = mean(value_numeric, na.rm = T)
  ) %>%
  ungroup() %>%
  select(taxon_name, resprouting_capacity = value_numeric) %>%
  distinct()


phytophthora_with_resprouting_capacity <- phytophthora %>%
  left_join(resprouting_capacity %>% rename(suggested_name = taxon_name)) %>%
  filter(!is.na(resprouting_capacity)) %>%
  select(suggested_name, susceptibility = `Susceptibility Rating`, resprouting_capacity) %>%
  mutate(
    susceptibility_simple = ifelse(str_detect(susceptibility, "resistant") & !str_detect(susceptibility, "susceptible"), "resistant", NA),
    susceptibility_simple = ifelse(!str_detect(susceptibility, "resistant") & str_detect(susceptibility, "susceptible"), "susceptible", susceptibility_simple),
    susceptibility_simple = ifelse(str_detect(susceptibility, "resistant") & str_detect(susceptibility, "susceptible"), NA, susceptibility_simple)
         ) %>%
  filter(!is.na(susceptibility_simple))

phytophthora_with_resprouting_capacity %>% group_by(susceptibility) %>% summarise(count = n()) %>% ungroup() %>% distinct()

ggplot(data = phytophthora_with_resprouting_capacity, aes(x = resprouting_capacity)) + geom_histogram() + facet_wrap(vars(susceptibility_simple))
```

```{r}
susceptible_myrtaceae <- read_csv("data/myrtaceae_susceptibility.csv") %>%
  rename(taxon_name = `Scientific Name`)
```

```{r}
susceptible_myrtaceae_LMA <- susceptible_myrtaceae %>% left_join(LMA_means, by = "taxon_name")

ggplot(data = susceptible_myrtaceae_LMA, aes(x = Susceptibilty_binary, y = value)) + geom_point()

model_LMA <- lm(value ~ Susceptibilty_binary, data = susceptible_myrtaceae_LMA)
```

```{r}
Begg <- read_csv("data/datasets_from_manuscripts/Beggs_2010_data.csv")

new_names <- APCalign::create_taxonomic_update_lookup(Begg$species) %>% select(original_name, accepted_name, suggested_name)

Begg <- Begg %>% left_join(new_names %>% rename(species = original_name))

categorical <- austraits$traits %>%
  filter(taxon_name %in% Begg$accepted_name) %>%
  filter(trait_name %in% c("plant_growth_form", "resprouting_capacity", "life_history", "vegetative_regeneration", "bud_bank_location", "seedbank_location", "photosynthetic_pathway")) %>%
  select(taxon_name, trait_name, value) %>%
  group_by(taxon_name, trait_name) %>%
  mutate(value = paste0(value, collapse = "-")) %>%
  ungroup() %>%
  distinct() %>%
  pivot_wider(names_from = trait_name, values_from = value)

numeric <- austraits$traits %>%
  filter(taxon_name %in% Begg$accepted_name) %>%
  filter(trait_name %in% c("leaf_mass_per_area", "leaf_N_per_dry_mass")) %>%
  select(taxon_name, trait_name, value) %>%
  group_by(taxon_name, trait_name) %>%
  summarise(value = mean(as.numeric(value))) %>%
  ungroup() %>%
  distinct() %>%
  pivot_wider(names_from = trait_name, values_from = value)


Begg_with_traits <- Begg %>% 
  left_join(categorical %>% rename(accepted_name = taxon_name)) %>%
  left_join(numeric %>% rename(accepted_name = taxon_name)) 
```



